[package]
name = "milo/game"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Cmdr = "evaera/cmdr@1.12.0"
DataService = "leifstout/dataservice@1.0.0"
React = "haedrix/react@17.3.10"
Networker = "leifstout/networker@0.3.1"
ReactRoblox = "haedrix/react-roblox@17.3.8"
UILabs = "rocky28447/ui-labs@0.1.0"
Signal = "sleitnick/signal@2.0.0"
Janitor = "howmanysmall/janitor@1.17.0"
Ripple = "littensy/ripple@0.10.0"
TopbarPlus = "1foreverhd/topbarplus@3.4.0"